challenges.html
main.js
style.css

Jenny and Henrik
we have added a filter button
started setup on the filterwindow layout.

Filter button

---

challenges.css
challenges.html
challenges.js
css/challenges.css
css/challenges.css.map
index.html
package-lock.json
package.json
src/challenges.scss

Fixed API that now loads to challenges.html via challenges.js script. 
CSS for grid (very basic at the moment) 
One existion red button takes user to challenges.html. (there will be more buttons with same functionality, and some "temporary buttons needs to be removed" )

API now loads to challenges.html site 

---

.gitignore
challenges.html
challenges.js
challenges_rating_sort.js
index.html
main.js

after our merge we had some small errors, have now fixed them.
also removed some code that had been added twice.

fixed some errors after merge

---

index.html

To make all challenge links load in to challenge.html.

Small change to index.html

---

main.js

Making a tryCatch block to catch error in getApiToArray in main.js. also moved export {array} outside the test to enable the array to have the content of the fetched and sorted values

Implementing tryCatch block to getApiToArray

---

filter.js
js/booking.js

Fixed the filtering for types online/on-site so that it will now show all the online/on-site cards if both are checked.
or just one type if only one is checked.

Type filtering fix

---

challenges.html
challenges.js
filter.js
style.css

- Added a text that says "no matching challenges".
- Added a  media query to the filter div.
- Added a trashcan to remove the selected filters.
- Made the cards responsive in the mobile version 
Worked with Henrik. And with Marcus on the cards.

No matching challenges

---

challenges.html
challenges.js
index.html
js/booking.js

group coding fixed some smaller things with the homepage style and setup eventlistener for open modual button

Final touches

---

challenges.js
style.css

Styled the back-to-top button into a gray arrow with a hover effect that turns it red and changes the scale.

Styling backtotop

---

js/booking.js
style.css

#Fixing red-button-small to the bottom left.
#Smaller fontsize to card__title
#Card__body to fill out space from image and button
#Spave between title and stars

Fixed styling of cards

---

__tests__/jest.test.js
challenges.html
challenges_test.md
filter_test.md
index.html
js/booking.js

fixed our datum problem with time slots adding on and never being removed

Datum changes

---

index.html

Added a new title to the og meta data

Added OG data for title

---

style.css

Added animation to the booking window with a slide-in- and opacity effect.

Booking window animation

---

style.css

I styled the booking window to look better in mobile version. Changed some margin and width. 
The website should already be responsive so I double checked everything else and it looks good in phone view.

Mobile version 

---

style.css

minor problem from merge, now fixed

 fixed merge problem in css file

---

card.css
challenges.css
challenges.html
challenges.js
index.html
main.js

Added an online or onsite icon to the cards.
Added div to fit h3 and i inside the div where the title used to be.

Icon for online or onsite type

---

style.css

fixed css issue with animation

---

challenges.js
style.css

Failed to load challenges text in index.html

---

filter.js
index.html
main.js

added filtering when pressing play online or play on-site. updated the href for alla links/button.
added function in filter.js.
-- please test ---
check all buttons on the page and make sure the shown cards are the correct online/on-site option.
check that filter window shows the type checkbox checked.

Querystring filter

---

style.css

found an run away } in css

---

filter.js

In the filter function the user can now type 3 character before it automatically searches for a room.

Automatic search after 3 characters

---

challenges.html
style.css

changed online and onsite nav link to challenges on challanges.html, added a active class that highlights while on challanges.html, added a icon to our filter button, and changed the font size

ux inprovments
